## **Daily Challenge: Data Handling and Analysis in Python**

In [1]:
import pandas as pd
df = pd.read_csv('datascience_salaries.csv')
df

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,149000
1,2,Data scientist,Full Time,Senior,Boston,USD,120000
2,3,Data scientist,Full Time,Senior,London,USD,68000
3,4,Data scientist,Full Time,Senior,Boston,USD,120000
4,5,Data scientist,Full Time,Senior,New York City,USD,149000
...,...,...,...,...,...,...,...
1166,2243,ML Ops,Full Time,Senior,Toronto,USD,228000
1167,2249,ML Ops,Full Time,Senior,Boston,USD,115000
1168,2250,ML Ops,Full Time,Senior,Delhi,USD,76000
1169,2255,ML Ops,Full Time,Senior,San Francisco,USD,68000
1170,2259,ML Ops,Internship,Senior,New York City,USD,135000

In [2]:
blank_salary = df['salary'].isna().any()
print('Presence of blank values within "salary" column:', blank_salary)

Presence of blank values within "salary" column: False

In [3]:
from sklearn.preprocessing import MinMaxScaler
salary_scaler = MinMaxScaler()
df['salary'] = salary_scaler.fit_transform(df[['salary']])
df[['salary']].head()

     salary
0  0.601010
1  0.454545
2  0.191919
3  0.454545
4  0.601010

In [4]:
df.to_csv('normalized_salary.csv', index=False)
df

,Unnamed: 0,job_title,job_type,experience_level,location,salary_currency,salary
0,0,Data scientist,Full Time,Senior,New York City,USD,0.601010
1,2,Data scientist,Full Time,Senior,Boston,USD,0.454545
2,3,Data scientist,Full Time,Senior,London,USD,0.191919
3,4,Data scientist,Full Time,Senior,Boston,USD,0.454545
4,5,Data scientist,Full Time,Senior,New York City,USD,0.601010
...,...,...,...,...,...,...,...
1166,2243,ML Ops,Full Time,Senior,Toronto,USD,1.000000
1167,2249,ML Ops,Full Time,Senior,Boston,USD,0.429293
1168,2250,ML Ops,Full Time,Senior,Delhi,USD,0.232323
1169,2255,ML Ops,Full Time,Senior,San Francisco,USD,0.191919
1170,2259,ML Ops,Internship,Senior,New York City,USD,0.530303

In [5]:
df = pd.read_csv('datascience_salaries.csv')

**Applying Principal Component Analysis (PCA) for Dimensionality Reduciton**

In [6]:
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
X = df.select_dtypes(include=['int64', 'float64']) # Selecting numeric columns only
X_scaled = StandardScaler().fit_transform(X) # Standardizing data
pca = PCA(n_components=2) #  Application of PCA
reduced_data = pca.fit_transform(X_scaled)
reduced_data

array([[ 0.81113185, -2.84693906],
       [ 0.18309452, -2.21453126],
       [-0.94586712, -1.0833844 ],
       ...,
       [ 1.68309499,  1.19786871],
       [ 1.51470356,  1.37718629],
       [ 2.97510547, -0.07447469]], shape=(1171, 2))

**Data Aggregation**

In [7]:
result = df.groupby('experience_level')['salary'].agg(['mean', 'median'])
print(result)

                          mean   median
experience_level
Entry             36111.111111  30000.0
Executive         76076.923077  46000.0
Mid               51786.885246  51000.0
Senior            75088.033012  68000.0