# **Data Preprocessing**

**Exploratory Data Analysis**

Loading dataset

In [31]:
import pandas as pd
df = pd.read_csv('../data/raw/feedback_data.csv')

Dataset Inspection

In [32]:
df.head()

   RespondentID                                           Feedback
0             1  Taste is nice but it's a bit pricey. Hope you ...
1             2  My morning feels incomplete without it. Custom...
2             3            Love this coffee. Not bad at all tbh. 👎
3             4                                  Expected better 👍
4             5                               Worth every penny. 😕

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 2 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   RespondentID  1500 non-null   int64
 1   Feedback      1500 non-null   str
dtypes: int64(1), str(1)
memory usage: 97.7 KB

In [34]:
df.describe()

       RespondentID
count   1500.000000
mean     750.500000
std      433.157015
min        1.000000
25%      375.750000
50%      750.500000
75%     1125.250000
max     1500.000000

In [35]:
df.isnull().sum()

RespondentID    0
Feedback        0
dtype: int64

In [36]:
df.duplicated().sum()

np.int64(0)

Rows: 1500  
Columns: 2  
Missing values: None  
Duplicated values: None  
  
Since no missing or duplicated values, no cleaning via 'drop' required.

**Text Preprocessing via the following steps**

* Lowercasing
* Removing punctiations
* Removing URLs, numbers and extra spacing
* Stopword removal
* Tokenization
* Lemmetization

In [61]:
#Lowercasing
df['Feedback'] = df['Feedback'].str.lower()

In [62]:
#Removing punctiation, URLs, numbers and extra spacing

In [63]:
#Stopword removal

In [64]:
#Tokenization

In [56]:
#Lemmetization